config:
  project_repos:
    o3webapp:
      repo: 'https://git.scc.kit.edu/synergy.o3as/o3webapp.git'
      branch: master
environment:
#  LANG: C.UTF-8

sqa_criteria:
  qc_style:
    repos:
      o3webapp:
        container: o3webapp-testing
        tox:
          tox_file: /o3webapp-testing/tox.ini
          testenv:
            - pep8
  qc_coverage:
    repos:
      o3webapp:
        container: o3webapp-testing
        tox:
          tox_file: /o3webapp-testing/tox.ini
          testenv: 
            - cover
            - cobertura
  qc_security:
    repos:
      o3webapp:
        container: o3webapp-testing
        tox:
          tox_file: /o3webapp-testing/tox.ini
          testenv:
            - bandit

timeout: 900
