# Dockerfile for development (direct copy of local directory)
# Dockerfile has two Arguments: base, tag
# base - base image (default: ubuntu, optional: debian)
# tag - tag for base mage (default: 20.04)
#
# To build the image:
# $ docker build -t <dockerhub_user>/<dockerhub_repo> --build-arg arg=value .
# or using default args:
# $ docker build -t <dockerhub_user>/<dockerhub_repo> .

# set the base image. default is ubuntu, optional debian
ARG base=ubuntu
# set the tag (e.g. latest, 20.04 for ubuntu; stable, stable-slim : for debian)
ARG tag=20.04

# Base image, e.g. debian:stable or ubuntu:bionic
FROM ${base}:${tag}

LABEL maintainer='XXX'
# o3webapp-be (backend) as a component of the Ozone assessment service

# Install system updates and tools
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends \
# Install system updates and tools
        git \
        nano \
        procps \
# Install system updates and tools
        python3-setuptools \
        python3-pip \
        python3-wheel && \
# Clean up & back to dialog front end
    apt-get autoremove -y && \
    apt-get clean -y && \
    rm -rf /var/lib/apt/lists/*
ENV DEBIAN_FRONTEND=dialog

WORKDIR /srv

# Copy code from the directory
COPY ./ o3webapp-be
WORKDIR /srv/o3webapp-be

# Install user app:
RUN pip3 install --no-cache-dir -e . && \
# Clean up
    rm -rf /root/.cache/pip/* && \
    rm -rf /tmp/*

# Set environments
ENV FLASK_APP o3webapp_be.backend.back_end.py
ENV LANG C.UTF-8
ENV O3API_URL http://o3api.test.fedcloud.eu:30509/api/
ENV EGI_TOKEN_URL https://aai-dev.egi.eu/oidc/token
ENV EGI_USERINFO_URL https://aai-dev.egi.eu/oidc/userinfo
ENV SECRET LTiU7yqg_GBCZlRjEVpctPOANIGjtzLGPFprIohg7pkOQ-Bl_iDEwjHdz9tBpL6qIiyN37SiJ83oLRrsv-qkpA
ENV PLOT_FOLDER o3webapp_be/backend/plot/

# Expose the port
EXPOSE 5000

# Start default script
CMD ["flask", "run", "--host", "0.0.0.0"]
